### ISSUE TITLE
Greengrass Core Version '1.9.0' is below minimum required version: '[1.10.0]

### ISSUE THREAD

**Issue by nanard52** [WAGO/aws-iot-greengrass#2]
Hello Guys,

Deployment 4be842dc-2cab-41fd-afe9-5b4fb7ca8ea2 of type NewDeployment for group 7fd62c84-c7db-4c89-8952-02857ea01246 failed error: Greengrass deployment error: unable to execute download step in deployment. error while downloading: error occurred while getting deployment: GetWithHeaders https://greengrass-ats.iot.eu-west-1.amazonaws.com:8443/greengrass/groups/7fd62c84-c7db-4c89-8952-02857ea01246/deployments/4be842dc-2cab-41fd-afe9-5b4fb7ca8ea2, statusCode: 400 Bad Request, error: {
  "code" : "IncompatibleGGCVersionException",
  "message" : "Greengrass Core Version '1.9.0' is below minimum required version: '[1.10.0]'"
}

**Comment by DirkMeihoefer** [comment]
Dockerfile updated for core version 1.11.6.
